cd /workspace/source

## head 1
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.0 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask00.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.3 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask30.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.5 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask50.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask30.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.7 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask70.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask50.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.8 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask80.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask70.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.85 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask85.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask80.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.9 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask90.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask85.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.95 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask95.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask90.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.97 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask97.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head1_embedding32_maxpmask95.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --lr=0.001 --GPU="0"

## head 2
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.0 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask00.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.3 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask30.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.5 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask50.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask30.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.7 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask70.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask50.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.8 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask80.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask70.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.85 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask85.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask80.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.9 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask90.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask85.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.95 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask95.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask90.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
python train_MET_VinDr-Mammo.py  --max_pct_mask=0.97 --embedding_dim=32 --model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask97.pth" --pretrained_model_name="saved_model/MET_VinDr-Mammo_Mass_enc6_dec3_head2_embedding32_maxpmask95.pth" --epochs=4000 --num_encoder_layers=6 --num_decoder_layers=3 --num_head=2 --lr=0.001 --GPU="0"
